# Generated by Django 3.1.1 on 2021-02-01 12:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('design', models.CharField(max_length=4000, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('params', models.CharField(max_length=2000, null=True)),
                ('result', models.CharField(max_length=4000, null=True)),
                ('state', models.CharField(default='1', max_length=1)),
                ('delete_state', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('admin', models.CharField(max_length=200, null=True)),
                ('developer', models.CharField(max_length=1000, null=True)),
                ('others', models.CharField(max_length=1000, null=True)),
                ('state', models.CharField(default='0', max_length=1)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('delete_state', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('account', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(default='1', max_length=1)),
                ('state', models.CharField(default='1', max_length=1)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('token', models.CharField(max_length=128, null=True)),
                ('token_time', models.IntegerField(null=True)),
                ('fail_times', models.IntegerField(default=0, null=True)),
                ('fail_date', models.DateField(null=True)),
                ('delete_state', models.CharField(default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=1000, null=True)),
                ('others', models.CharField(max_length=1000, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('delete_state', models.CharField(default='0', max_length=1)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.user')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, null=True)),
                ('detail', models.CharField(max_length=2000, null=True)),
                ('action_state', models.CharField(default='1', max_length=1)),
                ('ip', models.CharField(max_length=128, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.user')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('design', models.CharField(max_length=4000, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('params', models.CharField(max_length=2000, null=True)),
                ('result', models.CharField(max_length=4000, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('delete_state', models.CharField(default='0', max_length=1)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.interface')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.user')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.module'),
        ),
        migrations.AddField(
            model_name='interface',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.user'),
        ),
    ]
