# Generated by Django 3.1.1 on 2021-02-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_moduleuser_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
