# Generated by Django 3.1.1 on 2021-02-07 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_interface_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfacehistory',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
