# Generated by Django 3.1.1 on 2021-02-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_interfacehistory_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfacehistory',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
